package org.ml4j.nn.axons;

public enum TimingKey {

	LEFT_TO_RIGHT_CONV, LEFT_TO_RIGHT_FC, LEFT_TO_RIGHT_AVG, LEFT_TO_RIGHT_MAX,
	RIGHT_TO_LEFT_CONV, RIGHT_TO_LEFT_FC, RIGHT_TO_LEFT_AVG, RIGHT_TO_LEFT_MAX,
	REFORMAT_LEFT_TO_RIGHT_INPUT,  REFORMAT_LEFT_TO_RIGHT_OUTPUT, REFORMAT_RIGHT_TO_LEFT_INPUT, REFORMAT_RIGHT_TO_LEFT_OUTPUT_CONV, REFORMAT_RIGHT_TO_LEFT_OUTPUT_POOL, COMBINING;

	
}
